In [3]:
import numpy as np
a = np.array([1, 2, 4])
a1 = a
a1 

array([1, 2, 4])

In [4]:
a1[1] = 5
print(a1)
print(a)

[1 5 4]
[1 5 4]


In [5]:
a2 = a.copy()

In [7]:
print(a2)
print(a)

[1 5 4]
[1 5 4]


In [8]:
a2[0] = 6
print(a2)
print(a)

[6 5 4]
[1 5 4]


In [60]:
np.random.seed()
np.random.random()

0.7161936961774954

In [61]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [63]:
np.concatenate([a, a1])

array([1, 5, 4, 1, 5, 4])

In [70]:
b0 = np.array( [10, 20] )

In [71]:
b0

array([10, 20])

In [73]:
b0.shape

(2,)

In [67]:
b1 = np.array( [[10], [20]]   )

In [72]:
b1

array([[10],
       [20]])

In [69]:
b1.shape

(2, 1)

In [74]:
np.concatenate([b1, b1])

array([[10],
       [20],
       [10],
       [20]])

In [75]:
np.concatenate([b1, b1], axis = 0)

array([[10],
       [20],
       [10],
       [20]])

In [76]:
np.concatenate([b1, b1], axis = 1)

array([[10, 10],
       [20, 20]])

In [77]:
li = [[-3, -2, -1], [0, 1, 2]]
new = []
for i, j in enumerate(li):
    print(i, j)

0 [-3, -2, -1]
1 [0, 1, 2]


In [83]:
a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))

In [84]:
a

array([0, 1, 2])

In [85]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [86]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [87]:
b * a

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [88]:
np.dot(b, a)

array([-4,  5])

In [90]:
a.shape

(3,)

In [91]:
b.shape

(2, 3)

In [93]:
np.dot(a, b.T)

array([-4,  5])