In [1]:
import numpy as np

In [2]:
data_a = [1, 2, 3]
a = np.array(data_a)
print(a)

In [3]:
print(type(a))
print(a.shape)

In [4]:
data_b = [ [1, 2, 3], [4, 5, 6] ]
b = np.array(data_b)
print(b)

In [5]:
data_b1 = [ data_a, [4, 5, 6] ]
b1 = np.array(data_b1)
print(b1)

In [6]:
print(b.shape)

In [7]:
data_c = [0, 1, 2, 3, 4, 5]
c1 = np.array( data_c )
print(c1)

In [8]:
print(c1.shape)

In [9]:
c1.reshape(2, 3)

In [10]:
c1.shape

In [11]:
c2 = c1.reshape(2, 3)
print(c2)

In [12]:
print(c2.shape)

In [13]:
print(c2.ravel())
print(c2.ravel().shape)

In [14]:
print(c2.flatten())
print(c2.flatten().shape)

In [15]:
print(c2.reshape(-1, 1))
print(c2.reshape(-1, 1).shape)

In [16]:
c3 = c2.ravel()
print(c3)

In [17]:
c4 = c2.flatten()
print(c4)

In [18]:
c3[0] = 99
print(c3)

In [19]:
c2

In [20]:
c4

In [21]:
c4[0] = 77
c4

In [22]:
c2

In [23]:
a1 = [1, 2, 3]
a2 = a1

In [24]:
a2[0] = 99
a1

In [25]:
import copy
a3 = copy.copy(a1)
a3[0] = 66
a1s

In [26]:
a.dtype

dtype('int32')

In [27]:
d = np.array([1, 2], dtype= np.int16)
print(d)
d.dtype

[1 2]


dtype('int16')

In [28]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [29]:
d.dtype

dtype('int16')

In [30]:
d = d.astype(np.float16)
d.dtype

dtype('float16')

In [31]:
d

array([1., 2.], dtype=float16)

In [33]:
a

array([1, 2, 3])

In [32]:
a[0]

1

In [34]:
a[1:]

array([2, 3])

In [35]:
a[-1]

3

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
b[0]

array([1, 2, 3])

In [38]:
b[1, 0]

4

In [39]:
b[:, 2]

array([3, 6])

In [41]:
b[1,:]

array([4, 5, 6])

In [42]:
b[0, 1:]

array([2, 3])

In [43]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])